version: '3'
services:
  nginx:
    # https://hub.docker.com/_/nginx/
    image: nginx:1.25.0
    depends_on:
      - "app"
    ports:
      - "80:80"
    command:
      - "nginx"
      - "-g"
      - "daemon off;"
      - "-c"
      - "/etc/nginx/nginx.conf"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "socks:/mnt/socks"

  redis:
    # https://hub.docker.com/_/redis/
    image: redis:7.0.11

  mysql:
    # https://hub.docker.com/_/mysql/
    image: mysql:8.0
    command:
      - "--character-set-server=utf8mb4"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword

  app:
    # https://hub.docker.com/_/python/
    image: python:3.8.16-slim-bullseye
    depends_on:
      - "redis"
      - "mysql"
    command:
      - "python3"
      - "-m"
      - "http.server"
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings_dev
      - BASE_URL=http://localhost
      - REDIS_HOST=redis://redis/0
      - DB_HOST=db
      - DB_NAME=mysite
      - DB_USER=mysite
      - DB_PASS=mysite
      - http_proxy=http://proxy.uec.ac.jp:8080
      - https_proxy=http://proxy.uec.ac.jp:8080
    ports:
      - "8000:8000"
    volumes:
      - ".:/mnt/host"
      - "socks:/mnt/socks"

volumes:
  socks:
